version: '3.4'

services:
  app_test:
    container_name: app_test
    build:
      context: .
      dockerfile: test.Dockerfile
    restart: "no"
    networks:
      - netlocal

networks:
  netlocal:
    driver: bridge