version: '3.4'

services:
  todo-vue-test:
    container_name: todo-vue-test
    build:
      context: .
      dockerfile: test.Dockerfile
    restart: "no"
    networks:
      - netlocal

networks:
  netlocal:
    driver: bridge
