version: '3.4'

services:
  app:
    container_name: todo-vue
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - netlocal
    volumes:
      - /app/node_modules/
      - ./:/app
    environment:
      NODE_ENV: ${NODE_ENV:-dev}

networks:
  netlocal:
    driver: bridge
