version: '3'
services:
  app:
    container_name: todo-vue-app
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8080
    restart: always
    networks:
      - netlocal
    volumes:
      - /app/node_modules/
      - ./:/app
    environment:
      NODE_ENV: ${NODE_ENV:-dev}

  # test:
  #   container_name: todo-vue-test
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-test
  #   restart: "no"
  #   networks:
  #     - netlocal

networks:
  netlocal:
    driver: bridge