apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todoapp-ingress
  namespace: {{ .Values.todoapp.namespace }}

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: "todoapp.onaws.blackdevs.com.br"
    external-dns.alpha.kubernetes.io/ttl: 60

spec:
  tls:
    {{- toYaml .Values.ingress.spec.tls | nindent 4 }}
  rules:
    {{- toYaml .Values.ingress.spec.rules | nindent 4 }}
