apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  labels:
    component: todoapp
spec:
  type: {{ .Values.todoapp.service.type }}
  ports:
    - port: {{ .Values.todoapp.service.port }}
      targetPort: {{ .Values.todoapp.service.targetPort }}
  selector:
    component: todoapp
