apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: todoapp
  template:
    metadata:
      labels:
        component: todoapp
    spec:
      containers:
      - name: client
        image: juliocesarmidia/todo-vue:v1.0.0
        resources:
          limits:
            memory: "8Mi"
            cpu: "30m"
        ports:
        - name: todoapp-port
          containerPort: 80
      restartPolicy: Always
