apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp-hpa
  namespace: default

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todoapp-deployment

  minReplicas: 1
  maxReplicas: 10
  # targetCPUUtilizationPercentage: 80

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
