apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todoapp-ingress
  namespace: default

  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: kubernetes.blackdevs.com.br
  #   external-dns.alpha.kubernetes.io/ttl: "30"
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: todoapp-service
              servicePort: 80
