apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todoapp-ingress
  namespace: default

#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: 127.0.0.1.nip.io
#     external-dns.alpha.kubernetes.io/ttl: "30"
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /

# spec:
#   rules:
#     - host: 127.0.0.1.nip.io
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: todoapp-service
#               servicePort: 80

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: todoapp-service
              servicePort: 80
