version: v1.0.0

todoapp:
  replicaCount: 3
  image:
    repository: juliocesarmidia/todo-vue
    tag: v1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  secrets:
    NODE_ENV: invalid
  volumeMounts:
    name: cred-volume

ingress:
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      - http:
          paths:
            - path: /
              backend:
                serviceName: todoapp-service
                servicePort: 80

resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
