version: v1.0.0

todoapp:
  replicaCount: invalid
  namespace: invalid
  containerPort: 80
  image:
    repository: invalid
    tag: invalid
    imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: todoapp-port
  secrets:
    NODE_ENV: invalid
  resources:
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "300m"

certIssuer:
  awsAccess: invalid
  awsSecret: invalid
  hostedZoneID: invalid

ingress:
  spec:
    tls:
    - hosts:
      - todoapp.onaws.blackdevs.com.br
      secretName: todoapp-tls

    rules:
    - host: todoapp.onaws.blackdevs.com.br
      http:
        paths:
          - path: /
            backend:
              serviceName: todoapp-service
              servicePort: 80


nodeSelector: {}

tolerations: []

affinity: {}
